### ISSUE TITLE
Rolling update

### ISSUE THREAD

**Issue by urosgruber** [bsdci/libioc#459]
This is more of a question what would be best way to use ioc with combination of blue/green jail deployment. Creating jail with the same name but different tag will not work so I was trying with different naming schema and it turns out that anything other than [a-z0-9] and dash is not supported. I was able to use . within the jail name, but then I was unable to start the jail. Next thing come up to my mind was using multi pool scenario but then I got stuck with `ioc fetch -r blue/11.2-RELEASE` with the error that release *blue/11.2-RELEASE* is not available (<--- this is probably a bug?).

Anyone else using something similar. 

FYI at the moment I'm using a proprietary wrapper that handle the naming -> UUID translation and use uuid as jail name.

**Comment by gronke** [comment]
I would have recommended using the multi-pool feature for this task.

The bug you've described is confirmed.
