### ISSUE TITLE
Support for multiple NICs with configured addresses

### ISSUE THREAD

**Issue by gtz42** [bsdci/libioc#618]
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [ ] Supply `print(libioc.VERSION)`
- [ ] Supply the commands used, along with any steps to recreate it.
- [ ] Provide the output from the command you issued.
- [ ] Supply what you expected the result or output to be
- [ ] Checked that the problem has not already been fixed on `master` if using
 a stable release.

**Comment by gronke** [comment]
This is already supported.

```python3
>>> import libioc
>>> jail = libioc.Jail("myjail")
>>> jail.config["ip4_addr"] = "vnet0|192.168.23.2/24,vnet1|192.168.42.2/24"
>>> jail.config["ip4_addr"]
{'vnet0': AddressSet({IPv4Interface('192.168.23.2/24')}), 'vnet1': AddressSet({IPv4Interface('192.168.42.2/24')})}
>>> jail.save()
```

You can have multiple IP addresses on each interface as well as DHCP (or rtadv for IPv6).

Please keep in mind that you also need to configure your vnet interfaces before starting the jail:

```python
>>> jail.config["interfaces"] = "vnet0:bridge0,vnet1:bridge1"
>>> jail.config["interfaces"]
{'vnet0': <libioc.BridgeInterface.BridgeInterface object at 0x8025230f0>, 'vnet1': <libioc.BridgeInterface.BridgeInterface object at 0x802523128>}
```

**Comment by igalic** [comment]
This should go directly into the handbook.
And probably can, verbatim.
