### ISSUE TITLE
(help me) add provisioning method puppet

### ISSUE THREAD

**Issue by igalic** [bsdci/libioc#625]
Currently, i'm using `exec_start` to execute puppet on every startup, however, it seems it would be much easier if I could run it only once, at provisioning time.

I'd need some guidance to create such a provisioning plugin.

**Comment by xaque208** [comment]
You can do something like `cat script.sh | iocage exec j sh` after the first start.  This is effectively what's happening in that jail module you worked on a while back.  Works pretty well in puppet, but the pattern could be applied outside well enough if something were orchestrating the jail build.

**Comment by igalic** [comment]
it's turned out to be a little bit more elaborate… but for now we have #629
