### ISSUE TITLE
IP is not removed on destroy

### ISSUE THREAD

**Issue by urosgruber** [bsdci/libioc#659]
If you issue `ioc destroy myjail` IP alias is left as it is.

```
ioc create myjail ip4_addr="lo1|172.16.0.10"
ioc start myjail
ifconfig lo1 | grep 172.16.1.10
ioc stop myjail
ioc destroy myjail
ifconfig lo1 | grep 172.16.1.10
```
After that IP still attached to the interface. Using version **ioc, version 0.6.0 2019/02/08**

**Comment by gronke** [comment]
The usr.sbin/jail command automatically creates the IPv4 alias, but never removes it from the interface, which mirrors the behavior of the jail command.

@urosgruber what do you suggest should happen instead?

**Comment by urosgruber** [comment]
I understand `jail` does nothing to the IP after stop. But would be nice if `ioc` removes IP after destroy. I thought I'm doing something wrong.

**Comment by gronke** [comment]
> I thought I'm doing something wrong.

No, it just has not been implemented yet.

> But would be nice if `ioc` removes IP after destroy.

Seems reasonable. Let's do it!
