### ISSUE TITLE
Listing of releases should output dataset

### ISSUE THREAD

**Issue by urosgruber** [bsdci/libioc#708]
I think it would be nice to show dataset as well. Looks kinda confusing right now

`ioc list -r`

```
+--------------+
|  FULL_NAME   |
+==============+
| 11.2-RELEASE |
+--------------+
| 12.0-RELEASE |
+--------------+
| 11.2-RELEASE |
+--------------+
| 12.0-RELEASE |
+--------------+
```

**Comment by gronke** [comment]
For jails, libioc prints full identifiers (`<SOURCE_DATASET_NAME>/<JAIL_NAME>`) as soon as there is more than one dataset configured. The same should happen for release names.

**Comment by urosgruber** [comment]
Weird. I have two datasets and each have both releases. But there is not details of dataset and in case I would have some other release only on one of them I wouldn't know to what dataset release belongs.

**Comment by gronke** [comment]
> Weird. I have two datasets and each have both releases.

They are necessary to clone new jails from. Cloning across pools might not be possible, so libioc requires to have each release available on all source datasets.

> But there is not details of dataset and in case I would have some other release only on one of them I wouldn't know to what dataset release belongs.

Understood. The issue here is that `ioc list -r` does not support output columns. This is an issue of the CLI.

**Comment by urosgruber** [comment]
I guess this one can be closed then.
